### ISSUE TITLE
Verwaltung -> Benutzer -> Neu: E-Mail 

### ISSUE THREAD

**Issue by Josi-Conrad** [TIXI24/sfitixi#112]
Wird ein "Neuer Benutzer" (Rollen Admin, Manager oder Diponent) erfasst wird erwartet, dass automatisch ein E-Mail an die Geschäftsleitung ausgelöst wird mit der vorgenommen Änderung. Kontrollmöglichkeit wegen Missbrauch.

**Comment by Martin-Jonasse** [comment]
migrated to https://github.com/TIXI24/requirements/issues/34
