### ISSUE TITLE
FetchWorkingDayExistingChildren returning null causing the app to crash on new driving order

### ISSUE THREAD

**Issue by faustos** [TIXI24/sfitixi#189]
Class Tixi\App\AppBundle\Ride\RideManagementImpl 
Function checkDrivingMissionFeasibility

If no production plan exists, fetchWorkingDayExistingChildren on WorkingDayRepositoryDoctrine returns null. This causes the app to crash if checkDrivingMissionFeasibility is called (e.g. on new driving order)
![screen shot 2016-06-12 at 01 29 37](https://cloud.githubusercontent.com/assets/1834494/16019823/5db1c4f8-31ab-11e6-972a-8afcd354de6c.png)

**Comment by Martin-Jonasse** [comment]
fausto

In all test cases, at least one production plan with one day in the future must exist.

	Paradigm: Rolling planning with two or three months in the future.

The test case below should translate to expecting an error message: "Production Plan does not exist“.
Please open an new issue for this. Thank you.

Kind regards

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 13.06.2016 um 21:12 schrieb faustos <notifications@github.com>:

**Comment by Martin-Jonasse** [comment]
Fixed this (marked yellow):
![fixed](https://cloud.githubusercontent.com/assets/4991526/17408995/9e8c4c60-5a6d-11e6-8a6c-c421ae1daf59.PNG)
