### ISSUE TITLE
Information Disclosure

### ISSUE THREAD

**Issue by faustos** [TIXI24/sfitixi#204]
The project information page (http://dispo.tixizug.ch/home/about) reveals too much information about the underlying deployment system (especially information about LAMP stack). This is known as information disclosure and is considered to be an security risk.  

<img width="567" alt="screen shot 2016-08-22 at 12 25 50" src="https://cloud.githubusercontent.com/assets/1834494/17851694/ae74ca22-6863-11e6-9a6b-c04860e3cb77.png">

**Comment by Martin-Jonasse** [comment]
Kompromissvorschlag:

Wenn der Benutzer eingelogged ist, dann werden alle Informationen angezeigt.

Wenn der Benutzer nicht eingelogged ist (public), dann wird nur der erste Zeile angezeigt.

P.S. in die TIXI.YML Datei und Source Code steht noch viel mehr und heiklere Infos drin, 
=== ist das dann nicht auch ein Security Risk?

LbG Martin

Martin Jonasse
Seemattstrasse 38
6333 Hünenberg See
Privat:   041 780 76 12
Mobile: 079 832 69 10
------------------------------------------------------------

Am 22.08.2016 um 12:30 schrieb faustos <notifications@github.com>:

**Comment by Martin-Jonasse** [comment]
Fixed the About page as follows:
![screenshot 2016-10-14 10 32 33](https://cloud.githubusercontent.com/assets/4991526/19380901/9963fb70-91f9-11e6-872c-2f60fdaddcac.png)
