### ISSUE TITLE
Verwaltung -> Alle Fahrzeugdepots -> Neues Fahrzeugdepot -> tabulator!

### ISSUE THREAD

**Issue by Josi-Conrad** [TIXI24/sfitixi#99]
Adresse erfassen -> weiter mit Tabulator -> Adresse wird nicht übernommen!
 (siehe Snapshot)
![neuesdepotadresse](https://cloud.githubusercontent.com/assets/7513352/3888996/5c029b10-2207-11e4-9475-67d0f09bab1a.png)

Erwartet wird, dass man mit Tabulator ins nächste Feld springen kann und die gemachten Eingaben übernommen werden.

![fahrzeugdepot_snp-3](https://cloud.githubusercontent.com/assets/7513352/3889267/cd441520-220b-11e4-9959-f5670ae27ae4.PNG)

Google-Koordinaten werden erst übernommen, wenn nach -> PLZ Ort -> Marker bewegt wird!

![fahrzeugdepot_snp-4](https://cloud.githubusercontent.com/assets/7513352/3889268/d3529c52-220b-11e4-8d7d-0e8cbc491f70.PNG)

Test kann so nicht durchgeführt werden!

**Comment by Martin-Jonasse** [comment]
This is not a bug, the address data must be complete, always.
